[workspace]

members = [
    "tooltrain-data",
    "tooltrain-engine",
    "host",
    "example-programs/mastodon-feed",
    "core-programs/ls",
    "core-programs/file-explorer", "tooltrain-rust-guest",
]
exclude = ["program_template"]
resolver = "2"