[workspace]

members = [
    "commander-data",
    "commander-engine",
    "host",
    "example-programs/mastodon-feed",
    "core-programs/ls",
    "core-programs/file-explorer", "commander-rust-guest",
]
exclude = ["program_template"]
resolver = "2"